import {Component,inject,signal,OnInit,ChangeDetectionStrategy} from '@angular/core';import {FormsModule} from '@angular/forms';import {Api} from '../core/api';import {Meeting,Commitment} from '../core/models';
interface DeletionPreview {meeting_id:string;meeting_title:string;commitment_ids:string[];commitment_count:number;dependency_count:number;event_count:number;commitments:{id:string;title:string;owner:string;direct:boolean}[];other_meetings:{id:string;title:string}[]}
@Component({standalone:true,imports:[FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="eyebrow">CONVERSATION → COMMITMENT</div><h1>Meetings</h1><p>Capture genuine promises. Leave the rest as conversation.</p>
<div class="two-col"><section><h2>Add a conversation</h2><label>Meeting title<input [(ngModel)]="title" placeholder="Launch readiness / weekly sync"></label><label>Meeting date<input type="date" [(ngModel)]="heldOn"></label><label>Transcript<textarea rows="10" [(ngModel)]="transcript" placeholder="Sarah: I'll finish the QA report by Friday.
Alex: I'll deploy once Sarah approves the build."></textarea></label><button class="primary" [disabled]="api.busy()||!title||transcript.length<10" (click)="create()">Save & analyze transcript</button><button (click)="example()">Use example transcript</button></section>
<section><h2>Meeting history</h2>@for(m of meetings();track m.id){<button class="meeting-row" (click)="select(m)"><span><strong>{{m.title}}</strong><small>{{m.held_on}}</small></span><span class="badge">{{m.state}}</span></button>}@empty{<div class="empty">No meetings yet. Start with a transcript.</div>}</section></div>
@if(selected();as m){<section><div class="section-heading"><div><h2>{{m.title}}</h2><p>Review the interpretation before creating commitments.</p></div><button [disabled]="api.busy()" (click)="previewDelete(m)">Delete meeting</button>@if(m.state==='draft'){<button class="primary" [disabled]="api.busy()" (click)="analyze(m.id)">Analyze</button>}</div>
@if(deletion();as d){<div role="alert" style="border:1px solid #d9a79b;background:#fff4ef;padding:20px;margin:20px 0;border-radius:5px"><h3>Delete {{d.meeting_title}}?</h3><p>This permanently deletes this meeting and {{d.commitment_count}} commitments, including all promises connected through upstream or downstream dependencies.</p><p>{{d.dependency_count}} dependency links and {{d.event_count}} timeline events will be removed.</p>@if(d.other_meetings.length){<p><strong>Promises from other meetings are affected:</strong></p><ul>@for(other of d.other_meetings;track other.id){<li>{{other.title}}</li>}</ul><p>The other meetings themselves remain.</p>}<ul>@for(c of d.commitments;track c.id){<li>{{c.owner}} · {{c.title}} {{c.direct?'(related to this meeting)':'(linked dependency chain)'}}</li>}</ul><button style="background:#a7432b;color:white" [disabled]="api.busy()" (click)="confirmDelete()">Permanently delete meeting & commitments</button><button [disabled]="api.busy()" (click)="deletion.set(null)">Cancel</button></div>}
@if(m.state==='analyzed'){@for(f of m.findings;track $index){<div class="finding"><div class="section-heading"><span class="badge">{{f.kind}} · {{(f.confidence*100).toFixed(0)}}% confidence</span><select [(ngModel)]="f.action"><option value="ignore">Ignore</option><option value="confirm">Confirm promise</option><option value="link">Link existing promise</option></select></div><blockquote>{{f.statement}}</blockquote><p class="muted">{{f.explanation}}</p>@if(f.action!=='ignore'){<div class="form-grid"><label>Promise<input [(ngModel)]="f.title"></label><label>Owner<select [(ngModel)]="f.owner_id" (ngModelChange)="assign(f,$event)"><option [ngValue]="null">Choose owner (AI: {{f.owner}})</option>@for(u of api.users();track u.id){<option [value]="u.id">{{u.name}} · {{u.team}}</option>}</select></label><label>Deadline<input type="date" [(ngModel)]="f.due_date"></label><label>Waiting condition<input [(ngModel)]="f.condition"></label></div><label>Prerequisites from this meeting (Ctrl/Cmd to select several)<select multiple [(ngModel)]="f.depends_on_indices">@for(other of m.findings;track $index){@if(other!==f){<option [ngValue]="$index">{{other.owner}} · {{other.title}}</option>}}</select></label><label>Existing prerequisites<select multiple [(ngModel)]="f.prerequisite_ids">@for(c of commitments();track c.id){<option [value]="c.id">{{c.owner}} · {{c.title}}</option>}</select></label>@if(f.action==='link'){<label>Existing commitment<select [(ngModel)]="f.existing_id"><option [ngValue]="null">Choose a commitment</option>@for(c of commitments();track c.id){<option [value]="c.id">{{c.owner}} · {{c.title}}</option>}</select></label>}}</div>}
@if(!m.findings.length){<div class="empty">No meaningful statements detected. No commitments will be created.</div>}
<button class="primary" [disabled]="api.busy()" (click)="review(m)">Confirm review</button>}
@if(m.state==='reviewed'){<p class="success">Review saved. Linked promises retain their existing timeline.</p>}<details><summary>Original transcript</summary><pre>{{m.transcript}}</pre></details></section>}`})

export class Meetings implements OnInit {
 deletion=signal<DeletionPreview|null>(null);
 api=inject(Api);meetings=signal<Meeting[]>([]);commitments=signal<Commitment[]>([]);selected=signal<Meeting|null>(null);title='';heldOn=new Date().toISOString().slice(0,10);transcript='';
 async ngOnInit(){await this.load();}
 async load(){try{await this.api.loadUsers();this.meetings.set(await this.api.meetings());this.commitments.set(await this.api.commitments());}catch{}}
 select(m:Meeting){this.deletion.set(null);this.selected.set({...m,findings:m.findings.map(f=>({...f,owner_id:f.owner_id||this.api.users().find(u=>u.name.toLowerCase()===f.owner.toLowerCase())?.id||null,depends_on_indices:f.depends_on_indices||[],prerequisite_ids:f.prerequisite_ids||[],action:f.existing_id?'link':f.kind==='commitment'?'confirm':'ignore'}))});}
 example(){this.title='Launch readiness';this.transcript=`Sarah: I'll finish the QA report by tomorrow.
Alex: I'll deploy the release once QA approves the build.
Priya: We could consider a new landing page next quarter.
Alex: Could Sarah review the deployment checklist?
Sarah: I'll review the deployment checklist by tomorrow.`;}
 async create(){try{const m=await this.api.call<Meeting>('POST','/meetings',{title:this.title,held_on:this.heldOn,transcript:this.transcript});await this.load();this.select(m);await this.analyze(m.id);}catch{}}
 async analyze(id:string){try{this.select(await this.api.call<Meeting>('POST',`/meetings/${id}/analyze`));await this.load();}catch{}}
 assign(f:Meeting['findings'][number],id:string){f.owner=this.api.users().find(u=>u.id===id)?.name||f.owner;}
 async review(m:Meeting){if(m.findings.some(f=>f.action!=='ignore'&&(!f.owner_id||!f.owner.trim()||!f.title.trim()||(f.action==='link'&&!f.existing_id)))){this.api.error.set('Add an owner and promise; choose an existing commitment for every link.');return;}try{const result=await this.api.call<Meeting>('POST',`/meetings/${m.id}/review`,{items:m.findings.map((f,index)=>({index,action:f.action,title:f.title||'Ignored',owner:f.owner||'Unknown',owner_id:f.owner_id,due_date:f.due_date||null,condition:f.condition,existing_id:f.existing_id,depends_on_indices:f.depends_on_indices,prerequisite_ids:f.prerequisite_ids}))});this.select(result);this.api.changed();await this.load();}catch{}}
 async previewDelete(m:Meeting){try{this.deletion.set(await this.api.call<DeletionPreview>('GET',`/meetings/${m.id}/deletion-preview`));}catch{}}
 async confirmDelete(){const preview=this.deletion();if(!preview)return;try{await this.api.call('DELETE',`/meetings/${preview.meeting_id}`,{expected_commitment_ids:preview.commitment_ids});this.deletion.set(null);this.selected.set(null);this.api.changed();await this.load();}catch{this.deletion.set(null);}}

}
